megane-s/minshumi-frontend

- .vscode/ts.code-snippets
- .vscode/tsx.code-snippets
- README.md
> [Issue-2] スニペットの追加

- .vscode/ts.code-snippets
- .vscode/tsx.code-snippets
> zobjectのスニペットを追加

- .vscode/settings.json
- prisma/migrations/20231117101446_add_domain_model/migration.sql
- prisma/schema.prisma
- src/prisma/generated/index.ts
close #6 
- ER図をもとにモデルを作成
- [ER図](https://drive.google.com/file/d/13Hdx3YXLs7BX-uhPOLl4sAJLShpnUiQI/view?usp=drive_link)
- dev環境にマイグレート
出来を10点満点で自己評価:
6点
やり忘れているところありそう。
> [issue-6] ドメイン型を追加

- package.json
- yarn.lock
close #34 
framer motionを導入
出来を10点満点で自己評価:
点
レビューしない
> framer-motionを導入

- .github/workflows/pullRequestCheck.yaml
close #21 
出来を10点満点で自己評価:
7点
レビューしない
> PR時のチェックににbuildするjobを追加

- package.json
- yarn.lock
close #35 
出来を10点満点で自己評価:
点
レビューしない
> react-iconsを導入

- src/components/MutateButton.tsx
- src/util/client/useMutate.tsx
close #36 
出来を10点満点で自己評価:
8点
レビューしない
> MutateButtonを実装

- package.json
- prisma/migrations/20231121124640_add_art_description/migration.sql
- prisma/migrations/20231121124755_to_required_art_description/migration.sql
- prisma/migrations/20231121125401_add_business_card_image_url/migration.sql
- prisma/schema.prisma
- prisma/seed/art.ts
- prisma/seed/client.ts
- prisma/seed/faker.ts
- prisma/seed/index.ts
- prisma/seed/user.ts
- src/art/create.ts
- src/businessCard/create.ts
- src/prisma/generated/index.ts
- yarn.lock
close #80
- テスト用データをseedで用意 (dev DBに反映ずみ)
- 不足している列の追加
出来を10点満点で自己評価:
6点
レビューしない
> データベースモデルの不備を修正

- src/components/Dialog.tsx
close #79
useDialogの内容をリファクタリング
出来を10点満点で自己評価:
8点
> useDialogをリファクタリング

- .gitignore
- gcs-cors.json
- next.config.js
- package.json
- src/app/api/upload/route.ts
- src/file-upload/client.ts
- src/gcp/credentials.ts
- yarn.lock
close #83
- ファイルアップロードに関する処理を追加
https://github.com/megane-s/minshumi-frontend/assets/81161390/7bf69dca-ec0d-4b0c-a5f2-b00db1eaecd9
```tsx
const upload = useFileUpload() // {accept: "image/*} のように指定して選択できるファイルを指定できる
// Buttonを使ってアップロードボタンを追加
<Button onClick={upload.upload}>
画像をアップロードする
</Button>
// MutateButtonを使ってアップロードボタンを追加
// MutateButtonを使うことでButtonで実装した場合に加え、ローディング中などの処理が自動で追加される
<MutateButton mutation={upload}>
画像をアップロードする
</MutateButton>
// アップロードした画像のURLがupload.urlで取得できる
upload.url
```
出来を10点満点で自己評価:
7点
> [issue-83] ファイルアップロードユーティリティを追加

- .github/workflows/pullRequestCheck.yaml
close #96
出来を10点満点で自己評価:
7点
レビューしない
> CIにDATABASE_URL環境変数を指定

- prisma/schema.prisma
- prisma/seed/index.ts
- prisma/seed/recommendArt.ts
- prisma/seed/watchingArt.ts
- src/art/recommend/getByUser.tsx
- src/art/type.ts
close #93
- 好きな作品と今見ている作品のテストデータを追加
- 登録した好きな作品を取得する関数を追加
以下、追加したテストデータ
<details>
<summary>
好きな作品
</summary>
</details>
<details>
<summary>
今見ている作品
</summary>
</details>
出来を10点満点で自己評価:
8点
> [issue-93] データベースにテストデータを追加

- src/app/art/[art_id]/GoodButton.tsx
- src/app/art/[art_id]/actions.tsx
- src/app/art/[art_id]/page.tsx
- src/art/good/isGooded.ts
- src/art/tag/getTags.ts
close #51
作品詳細画面の追加
出来を10点満点で自己評価:
6点
> [Issue 51] 作品詳細の追加

- src/app/BaseLayout/Header.module.css
- src/app/BaseLayout/Header.tsx
- src/app/BaseLayout/HeaderMenu.tsx
close #91
ヘッダーのメニューをバーガーに変更
出来を10点満点で自己評価:
8点
> [issue-91] ヘッダーのメニューをバーガーに変更

- package.json
- prisma/migrations/20231207073647_add_comment_user_for_business_card_comment/migration.sql
- prisma/schema.prisma
- prisma/seed/watchingArt.ts
- src/businessCard/comment/create.ts
- src/prisma/generated/index.ts
- yarn.lock
> BusinessCardCommentにコメントしたユーザを追加

- src/app/BaseLayout/HeaderMenu.tsx
close #106
- メニューにログアウトボタンを追加
- ログイン時、ヘッダー上部のメニューにログアウトボタンがあり、ログアウトできることを確認。
出来を10点満点で自己評価:
8点
他にログアウトボタンいるところがあったら指摘お願いします🙇
> [issue-106] メニューにログアウトボタンを実装

- .eslintrc.js
close #110 
ESLintの設定を修正して、`onClick={someAsyncFunction}` と書けるように（`onClick={()=>void someAsyncFunction()}`としなくてもいいようになった）
なし
出来を10点満点で自己評価:
7点
- [x 実装できたのでチェックして欲しい。
> [issue-110] ESLintの設定の修正

- src/app/art/search/SearchResultList.tsx
- src/app/art/search/page.module.css
- src/app/art/search/page.tsx
- src/app/page.tsx
- src/app/search.tsx
- src/art/search.ts
close #55
作品の検索画面の実装
文字を入力し検索すると作品が出るようになった。
ローディングも追加できた。
出来を10点満点で自己評価:
8点
作品の検索結果がランダムになっているので変える必要あり。
> [issue-55] 作品の検索画面の実装

- src/app/debug/Content.tsx
- src/components/MutateButton.tsx
- src/util/client/useMutate.tsx
close #118
- useMutateに `loading` オプションを修正
https://github.com/megane-s/minshumi-frontend/assets/81161390/7305965d-8d72-458f-8ab6-21a1e2abecaa
出来を10点満点で自己評価:
7点
- `loading`に修正を加えたので、マージ前のコードで影響がある可能性があるので要注意。
> [issue-118] useMutateのローティングトーストを実装

- prisma/migrations/20231218030419_update_business_card_comment_good_user_fk/migration.sql
- prisma/schema.prisma
- src/app/user/[user_id]/ArtDetailDialog.tsx
- src/app/user/[user_id]/ArtImage.tsx
- src/app/user/[user_id]/CommentForm.tsx
- src/app/user/[user_id]/CommentListItem.tsx
- src/app/user/[user_id]/DeleteConfirmCommentDialog.tsx
- src/app/user/[user_id]/FollowButton.tsx
- src/app/user/[user_id]/LikeArtImage.tsx
- src/app/user/[user_id]/LikeButton.tsx
- src/app/user/[user_id]/actions.ts
- src/app/user/[user_id]/page.tsx
- src/app/user/[user_id]/styles.module.css
- src/businessCard/comment/get.ts
- src/businessCard/comment/getByBusinessCard.ts
- src/businessCard/comment/good/isGooded.ts
- src/businessCard/getById.ts
- src/user/follow/cancel.ts
- src/user/follow/follow.ts
- src/user/follow/getFollowers.ts
- src/user/follow/getFollowings.ts
close #58 
プロフィール画面の追加
http://localhost:3000/user/test-user-4
http://localhost:3000/art/test-art-4
http://localhost:3000/user/test-user-2
http://localhost:3000/art/test-art-1
出来を10点満点で自己評価:
5点
カルーセル未実装、名刺の表示未実装
> Issue 58 プロフィール画面

- prisma/migrations/20231220050335_add_create_and_update_at_to_business_card_comment/migration.sql
- prisma/schema.prisma
- src/businessCard/comment/getByBusinessCard.ts
- src/prisma/generated/index.ts
close #130 
コメントの順序が古い順になっていたので新しい順になるよう修正
- BusinessCardCommentテーブルにcreateAt, updateAtを追加
- `yarn dev` → [http://localhost:3000/user/test-user-4](http://localhost:3000/user/test-user-4)などにアクセスしてコメントが上から新しい順に並んでいることを確認。
出来を10点満点で自己評価:
8点
> [issue-130] コメントを新しい順になるように修正

- src/app/BaseLayout/HeaderMenu.tsx
close #133 
メニュー選択時にドロワーを閉じるように修正
出来を10点満点で自己評価:
8点
> [issue-133] メニュー選択時ドロワーを閉じるように修正

- src/app/profile/new/FirstRegisterTagsForm.tsx
- src/app/profile/new/actions.ts
- src/app/profile/new/page.tsx
- src/auth/server/options.ts
- src/components/icon/Check.tsx
- src/user/firstRegister.ts
- src/user/type.ts
close #49 
初期登録画面の実装
出来を10点満点で自己評価:
7点
レビューしない
> [issue-49] 初期登録画面

- package.json
> docker build 用にscriptを修正

- .github/workflows/deployMain.yaml
close #
https://github.com/megane-s/minshumi-frontend/actions/runs/7371651422
出来を10点満点で自己評価:
点
> [issue-59] mainデプロイが失敗したので修正

- .github/workflows/deployMain.yaml
> [issue-151] secret manager参照時のバージョンをlatest指定にする

- workers/src/index.ts
> リバースプロキシを修正

- workers/src/index.ts
close #
Originが送信されない都合でServer Actionsがエラーになっていた件を修正
出来を10点満点で自己評価:
6点
> workersでサーバアクションが動作しないバグを修正

- src/app/user/[user_id]/page.tsx
close #167
プロフィール画面の今見ている作品と好きな作品を上下を変更
　　　　　　　　　　　⇩
出来を10点満点で自己評価:
10点
> [issue-167] プロフィール画面の今見ている作品と好きな作品を上下を変更

- prisma/migrations/20240113081552_add_custom_art_tag_type/migration.sql
- prisma/schema.prisma
- src/app/art/[art_id]/appeal/page.tsx
- src/app/art/[art_id]/edit/layout.tsx
- src/app/art/[art_id]/edit/page.tsx
- src/app/art/[art_id]/edit/tag/EditArtTagForm.tsx
- src/app/art/[art_id]/edit/tag/actions.ts
- src/app/art/[art_id]/edit/tag/page.tsx
- src/app/art/new/tag/Form.tsx
- src/app/businesscard/new/actions.ts
- src/app/profile/new/FirstRegisterTagsForm.tsx
- src/app/profile/new/page.tsx
- src/app/user/[user_id]/actions.ts
- src/art/components/tag/ArtTagForm.tsx
- src/art/components/tag/tags.ts
- src/art/type.ts
- src/components/CenterizedScroll.tsx
- src/file-upload/client.ts
- src/prisma/generated/index.ts
- src/user/follow/cancel.ts
close #175
close #176
- 独自のタグを入力できるように
- 前後に見た作品のUIを修正
出来を10点満点で自己評価:
6点
時間がないのレビューしない
> 作品詳細・おすすめ周りのバグを修正

- src/app/api/businesscard/image/route.ts
- src/app/art/[art_id]/edit/detail/EditInputDetailForm.tsx
- src/app/art/[art_id]/edit/detail/actions.ts
- src/app/art/[art_id]/edit/detail/page.tsx
- src/app/art/new/detail/Form.tsx
- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/BusinessCardPreview.tsx
- src/app/businesscard/[businesscard_id]/edit/actions.ts
- src/app/businesscard/[businesscard_id]/edit/loading.tsx
- src/app/businesscard/[businesscard_id]/edit/page.tsx
- src/app/businesscard/new/SelectType.tsx
- src/app/businesscard/new/actions.ts
- src/app/user/[user_id]/actions.ts
- src/art/components/detail/ArtDetailForm.tsx
- src/art/tag/update.ts
- src/art/update.ts
- src/businessCard/defaults.ts
- src/businessCard/update.ts
- src/util/validation.ts
close #30
- [権限周りの設計書](https://docs.google.com/spreadsheets/d/1XeEypaHZPX73YsBQ6ic_ZhY9tkGyYAMl1im7gr_IwjY/edit#gid=0)をもとに実装した
- 各処理について
　　- 不正なユーザが操作を実行できないことを確認
　　- 正しいユーザが操作を実行できることを確認
　　- 検証したらどんなユーザでできた/できなかったかをコメントしてくれると嬉しい
特になし
出来を10点満点で自己評価:
7点
今回はあくまでDBに保存させないようにすることのみ実装しました。
不正なユーザの場合はそもそも画面に遷移させない、ログイン画面を出すなどの処理は別途対応していきたい
> [issue-30] 権限に関する処理を追加

- src/app/api/businesscard/image/route.ts
- src/app/api/businesscard/preview/route.ts
- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/BusinessCardPreview.tsx
- src/app/businesscard/[businesscard_id]/settings/page.tsx
- src/app/businesscard/new/SelectType.tsx
- src/app/settings/user/UserSettingForm.tsx
- src/app/settings/user/actions.ts
- src/app/settings/user/page.tsx
- src/components/ImageInput/Background.tsx
- src/components/ImageInput/Icon.tsx
- src/components/ImageInput/index.tsx
- src/components/ImageInput/type.ts
- src/components/icon/AddIcon.tsx
close #159
設定画面のユーザタブを実装。
出来を10点満点で自己評価:
6点
時間がないのでレビューしない
上の方の余白は共通部分のissue(#158) で実装 ([参考](https://github.com/megane-s/minshumi-frontend/issues/158#issuecomment-1890989340))
> [issue-159] 設定画面のユーザタブ 実装

- src/app/settings/watching-arts/WatchingArtsSettingForm.tsx
- src/app/settings/watching-arts/new/NewWatchingArtForm.tsx
- src/app/settings/watching-arts/new/actions.ts
- src/app/settings/watching-arts/new/page.tsx
- src/app/settings/watching-arts/page.tsx
- src/app/user/[user_id]/WatchingArtList/WatchingArtImage.tsx
- src/app/user/[user_id]/WatchingArtList/index.tsx
- src/app/user/[user_id]/actions.ts
- src/art/components/SelectArt.tsx
close #161 
出来を10点満点で自己評価:
点
時間ないのでレビューしない
> [issue-161] 設定画面の鑑賞中の作品タブを実装

- prisma/migrations/20240114225942_drop_comment_good/migration.sql
- prisma/migrations/20240114230304_drop_comment/migration.sql
- prisma/migrations/20240114230702_update_comments/migration.sql
- prisma/schema.prisma
- src/prisma/generated/index.ts
> [issue-177] DBの変更

- src/art/create.ts
> 作品が作成できないバグを修正

- src/app/BaseLayout/HeaderAvatar.tsx
- src/components/icon/Businesscard.tsx
close #224 
ログインメニューに名刺の登録ボタンを追加
出来を10点満点で自己評価:
10点
> [issue-224] ログインメニューに名刺の登録ボタンを追加

- src/app/BaseLayout/HeaderAvatar.tsx
close #228 
設定アイコンのURL先を変更
出来を10点満点で自己評価:
8点
> [issue-228]設定アイコンのURLを変更

- src/app/settings/layout.tsx
close #236 
設定タブの名前を好きな作品からアピール作品に変更
↓
出来を10点満点で自己評価:
10点
> [issue-236] タブの名前を変更

- src/app/user/[user_id]/Comments/Comments.tsx
> [issue-235] コメントの上下を修正

- src/app/art/[art_id]/edit/detail/actions.ts
- src/app/art/[art_id]/edit/tag/actions.ts
> [issue234] 保存後 作品の詳細ページへ遷移するように修正

- src/art/tag/interest/update.ts
- src/user/firstRegister.ts
close #232
close #240
出来を10点満点で自己評価:
点
> [issue-232] 初期登録のロジックを修正

- prisma/migrations/20240118155046_update_cascade_delete/migration.sql
- prisma/schema.prisma
[issue-253] 初期登録のロジックを修正
close #253 
いい機会なので必要そうなところ全てでカスケード削除できるようにしました。
- DBスキーマの修正
出来を10点満点で自己評価:
7点
最近時間がなくてさらっとレビューすることが増えてますが、今後に影響しかねない内容になるのでしっかりレビューをお願いします。
> [issue-232] カスケード削除できるようにDBを修正

- src/app/art/[art_id]/appeal/page.tsx
- src/art/getRelated.ts
close #239 
アピール一覧を取得するときにユーザIDによる絞り込みがなかったため起こっていた模様。
ユーザIDも絞り込み条件に入れるように修正した。
| | | |
|---|---|---|
|<img width="1427" alt="スクリーンショット 2024-01-19 1 27 17" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/85575ddc-b9be-44b3-b2ec-f994520f8c75"> | -> 別のユーザでログインし直すと... -> | <img width="1427" alt="スクリーンショット 2024-01-19 1 26 51" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/7945b470-30bc-4aee-883a-b65269d36a6d">|
出来を10点満点で自己評価:
7点
> [issue-239] 作品アピール編集で他の人が登録した前後に見た作品出てくるバグを修正

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/InputArtTitle.tsx
- src/art/components/SelectArt.tsx
> 名刺編集画面の作品の選択のUIの修正

- prisma/migrations/20240118155046_update_cascade_delete/migration.sql
- prisma/migrations/20240119232404_add_art_edit_history/migration.sql
- prisma/schema.prisma
- src/prisma/generated/index.ts
#170 のDBの変更
出来を10点満点で自己評価:
3点
レビューしない
> 作品更新時に履歴を残す - DBの修正

- prisma/migrations/20240120003840_add_art_tags_edit_history/migration.sql
- prisma/migrations/20240120050410_add_art_tags_edit_history/migration.sql
- prisma/migrations/20240120050707_sync/migration.sql
- prisma/schema.prisma
- src/app/art/[art_id]/AppealReminderDialog.tsx
- src/app/art/[art_id]/actions.tsx
- src/app/art/[art_id]/edit/detail/actions.ts
- src/app/art/[art_id]/edit/tag/actions.ts
- src/art/create.ts
- src/art/tag/update.ts
- src/art/update.ts
- src/prisma/generated/index.ts
close #171
- 作品の登録時・更新時に編集履歴を残すように
出来を10点満点で自己評価:
6点
レビューしない
> [issue-171] 作品の編集履歴

- prisma/migrations/20240120121454_/migration.sql
- prisma/migrations/20240120123605_fix_business_card_like_art_no/migration.sql
- prisma/migrations/20240120123931_fix_business_card_like_art_pk/migration.sql
- prisma/migrations/20240120130348_/migration.sql
- prisma/schema.prisma
- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/InputArtTitle.tsx
- src/app/businesscard/[businesscard_id]/edit/actions.ts
- src/app/businesscard/[businesscard_id]/settings/PublishForm.tsx
- src/app/businesscard/[businesscard_id]/settings/page.tsx
- src/app/search/art/SearchResultList.tsx
- src/app/search/user/SearchResultList.tsx
- src/app/tag/[tag_id]/page.tsx
- src/app/user/[user_id]/Comments/Comments.tsx
- src/art/components/SelectArt.tsx
- src/art/update.ts
- src/businessCard/create.ts
- src/businessCard/update.ts
- src/file-upload/client.ts
- src/prisma/generated/index.ts
> [Issue 237] 名刺作成ページ周りの修正

- src/art/getSuggestions.ts
- src/art/search.ts
- src/art/tag/getArts.ts
- src/tools/apply-arts-to-prod-db/README.md
> [Issue 261] 作品データ投入スクリプトの作成 と 開発環境への作品データ投入

- prisma/migrations/20240122045645_add_target_user_to_user_comment/migration.sql
- prisma/schema.prisma
- src/app/user/[user_id]/Comments/CommentForm/Content.tsx
- src/app/user/[user_id]/Comments/CommentForm/index.tsx
- src/app/user/[user_id]/Comments/Comments.tsx
- src/app/user/[user_id]/page.tsx
- src/prisma/generated/index.ts
- src/user/comment/create.ts
- src/user/comment/get.ts
> [Issue 282] プロフィール画面に表示されているコメントの修正

- src/app/settings/watching-arts/new/NewWatchingArtForm.tsx
close #273 
今見ている作品タブ内でこの中にないをクリックしたときに作品登録画面に飛ぶように修正しました。
設定の今見ている作品タブに行き、作品を登録ボタンを押し、この中にないをクリックし、作品登録画面に遷移
出来を10点満点で自己評価:
10点
> [issue-273] 設定-今見ている作品の修正

- src/app/user/[user_id]/Comments/CommentList/CommentListItem.tsx
close #256
日付の実装
コメントを投稿
出来を10点満点で自己評価:
7点
> [Issue-256]コメント投稿日付の実装

- src/app/businesscard/[businesscard_id]/edit/InputArtTitle.tsx
> [issue-278] InputArtTitleのドロップダウンの高さを調整

- package.json
- src/app/art/[art_id]/GoodButton.tsx
- src/app/art/[art_id]/appeal/Navigation.tsx
- src/app/provider.tsx
- src/app/user/[user_id]/Comments/CommentList/index.tsx
- src/app/user/[user_id]/Comments/Comments.tsx
- src/app/user/[user_id]/page.tsx
- yarn.lock
close #202
- アピール登録と作品のいいねのアニメーションを実装
https://github.com/megane-s/minshumi-frontend/assets/81161390/ed1c8fd6-2ad2-4c36-a846-b28d17785dd7
https://github.com/megane-s/minshumi-frontend/assets/81161390/ab91b8e6-c21f-4bf1-a5d5-9c7f3569c290
出来を10点満点で自己評価:
6点
> [Issue 202] アピール登録時と作品いいねのアニメーション実装

- prisma/migrations/20240123064512_add_indices/migration.sql
- prisma/migrations/20240123064936_fix_related_art_pk/migration.sql
- prisma/schema.prisma
- src/art/related/update.ts
close #66 
- indexを設定
- ついでに ほかの人がアピールの関連作品に同じ作品を登録すると消えるバグも修正
出来を10点満点で自己評価:
6点
> [Issue 66] データベースのインデックスを追加

- prisma/migrations/20240123135258_fix_search_id_to_recommend_id/migration.sql
- prisma/schema.prisma
- src/prisma/generated/index.ts
close #
出来を10点満点で自己評価:
点
レビューしない
> レコメンドエンジン向けのDBの修正

- src/app/BaseLayout/Footer.tsx
- src/app/BaseLayout/Header.tsx
- src/app/BaseLayout/HeaderDrawerMenu.tsx
close #299 
ヘッダー、ヘッダードロワー、フッター
出来を10点満点で自己評価:
8点
> [Issue-299]ロゴリンクでトップに戻る

- .github/workflows/deployMain.yaml
> cloud run の memory を更新

- src/app/BaseLayout/HeaderDrawerMenu.tsx
close #303
表題通り
出来を10点満点で自己評価:
8点
> [issue-303]リンクをクリックしてもドロワーが閉じるようにする

- src/app/user/[user_id]/ProfileBusinessCard.tsx
- src/app/user/[user_id]/page.tsx
- src/components/icon/AlertIcon.tsx
close #198
|||
|---|---|
|名刺を設定したユーザ|<img width="1186" alt="スクリーンショット 2024-01-25 15 12 31" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/b1ef8812-52f9-4165-a3b0-c146006466ac">|
|名刺を設定していないユーザ (自分以外)|<img width="1186" alt="スクリーンショット 2024-01-25 15 10 48" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/a5d79c6f-292c-4f71-bac1-6462ddd9dd4b">|
|名刺を設定していないユーザ (自分)|<img width="1186" alt="スクリーンショット 2024-01-25 15 10 58" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/6291f40c-33d3-407e-b2c2-180fcf11c6d3">|
出来を10点満点で自己評価:
8点
> [issue-198] プロフィール画面で後回しにしていたところの実装

- src/app/user/[user_id]/LikeArtList/LikeArtImage.tsx
- src/app/user/[user_id]/WatchingArtList/WatchingArtImage.tsx
> [issue-311] プロフィール画面にある作品をカーソルに合わせると指マークにする

- src/app/user/[user_id]/Comments/CommentList/CommentListItem.tsx
close #301
表題通り
出来を10点満点で自己評価:
7点
> [issue-301]コメントのユーザーのアバター、名前を押してユーザのプロフィール画面へ遷移する

- src/businessCard/buildImageUrlParams.ts
close #289
- 画像URLの `interestTags` になってたところを `interest_tags` に修正
出来を10点満点で自己評価:
6点
ブランチ名がかわいいのはご愛嬌
> [issue 289] 名刺のURLを修正

- src/notification/get.ts
- src/notification/send.ts
> 通知の取得ロジックを修正

- src/app/BaseLayout/Header.tsx
- src/app/notification/NotificationItem.tsx
- src/app/notification/page.tsx
- src/app/notification/recommendations/page.tsx
- src/app/user/[user_id]/Comments/CommentList/CommentListItem.tsx
- src/components/DateView.tsx
- src/notification/get.ts
close #
お知らせ画面の実装
出来を10点満点で自己評価:
8点
> [issue-60-ui] お知らせ画面の実装

- .github/workflows/deployMain.yaml
> github actionsを手動起動可能に構成

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/page.tsx
- src/app/businesscard/new/actions.ts
- src/businessCard/defaults.ts
close #326
画像が以下からランダムで選択されるように
(アイコンに関してはログインしているときはそのユーザのアイコンを使用するように)
出来を10点満点で自己評価:
点
> [issue-326] 名刺作成画面のデフォルト値を修正

- prisma/migrations/20240129065222_add_read_flag_to_notification/migration.sql
- prisma/schema.prisma
- src/app/notification/NotificationItem.tsx
- src/app/notification/loading.tsx
- src/app/notification/page.tsx
- src/app/notification/recommendations/page.tsx
- src/notification/get.ts
- src/prisma/generated/index.ts
> [Issue 333 db] 通知に既読をつける処理の実装

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/InputImages.tsx
close #337 
- 先生からの指摘点含めUIを修正
出来を10点満点で自己評価:
7点
> [issue-337] 名刺編集画面の修正

- src/app/search/(search)/art/SearchResultList.tsx
- src/app/search/(search)/art/page.tsx
- src/app/search/(search)/user/SearchResultList.tsx
- src/app/search/(search)/user/page.tsx
- src/app/settings/appeals/AppealSettingForm.tsx
- src/app/settings/user/UserSettingForm.tsx
- src/app/settings/watching-arts/WatchingArtsSettingForm.tsx
- src/app/tag/[tag_id]/page.tsx
- src/app/user/[user_id]/Comments/Comments.tsx
- src/app/user/[user_id]/LikeArtList/index.tsx
- src/app/user/[user_id]/WatchingArtList/index.tsx
close #314
スマホ用に文字の改行を修正
出来を10点満点で自己評価:
6点
スマホのサイズはiPhone14 pro maxを使って検証しました
> [issue-314]0件表示でスマホ画面の時に文字がファンキーにならないように調整

- src/app/search/(search)/layout.tsx
- src/components/SearchBar.tsx
close #329 
- テキストフィールドでエンターを押したときに検索画面に遷移するように
出来を10点満点で自己評価:
点
> [issue-329] SearchBar周りのUIの修正

- src/businessCard/defaults.ts
名刺の背景の画像を追加
<details>
<summary>画像一覧</summary>
</details>
出来を10点満点で自己評価:
7点
> 名刺の画像を追加してデフォ画像を更新

- src/app/art/[art_id]/appeal/Navigation.tsx
- src/app/art/[art_id]/page.tsx
close #203
アピールされてる作品ならアイコンを表示するように修正
出来を10点満点で自己評価:
10点
アイコンの表示の仕方がこれでいいのかが心配です。
// アピール済みアイコン
const AppealedIcon = () => (
<span role="img" aria-label="Appealed" style={{ marginLeft: "0.5rem" }}>
✅
</span>
);
> [issue-203] アピールされてる作品ならアイコンを表示するように修正

- src/app/ArtsList.tsx
- src/app/BaseLayout/Header.tsx
- src/app/TopNews.tsx
- src/app/art/[art_id]/page.tsx
- src/app/error.tsx
- src/app/not-found.tsx
- src/app/page.tsx
- src/components/SearchBar.tsx
#89 に関連
LCP画像にpriorityを設定
出来を10点満点で自己評価:
7点
> [issue-89] 画像周りの改善

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/page.tsx
> [issue-362] 既存の名刺を編集しようとしても作品がリセットされるバグを修正

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
close #360
称号という文言を肩書きに変更
出来を10点満点で自己評価:
7点
- x] 実装できたのでチェックして欲しい。
> "称号" を "肩書き" に修正

- src/app/art/[art_id]/AppealReminderDialog.tsx
- src/prisma/index.ts
close #366
https://github.com/megane-s/minshumi-frontend/assets/81161390/707abf64-b258-4df7-bd3c-33c120b189b0
出来を10点満点で自己評価:
7点
> [issue-366] アピール催促が表示されないバグを修正

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/new/SelectType.tsx
- src/app/businesscard/new/actions.ts
- src/app/profile/new/FirstRegisterTagsForm.tsx
- src/app/profile/new/actions.ts
close #267
出来を10点満点で自己評価:
7点
実装を変えた各画面について、リダイレクトがきちんとされるかのテストもお願いしたいです🙏
> [issue-267] router.pushをserver actionsでのredirectに変更

- src/app/TopNews.tsx
close #370
表題通り
出来を10点満点で自己評価:
10点
> トップパネルのpanel2をクリックしたときのリンク先をart/appealに変更

- src/app/settings/user/UserSettingForm.tsx
- src/app/user/[user_id]/LikeArtList/index.tsx
- src/app/user/[user_id]/WatchingArtList/index.tsx
- src/app/user/[user_id]/page.tsx
> カルーセル付きの0件表示を修正

- src/app/businesscard/[businesscard_id]/edit/page.tsx
> [issue-371] バグのもとになる記述を修正

- src/app/tag/[tag_id]/page.tsx
> [issue-376] タグのページネーションを0から1に変える

- src/app/settings/appeals/AppealSettingForm.tsx
close #380
/art/appealに変更
出来を10点満点で自己評価:
10点
> [issue-380]URL変更

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/page.tsx
- src/app/businesscard/new/actions.ts
> [Iissue-384] 名刺タイプ3の時に肩書きを入力できないように

- src/app/art/[art_id]/page.tsx
> [issue387] 自動改行するように修正

- src/art/create.ts
- src/art/search.ts
- src/user/search.ts
> 検索のロジックをLIKE句に変更

- next.config.js
- package.json
- src/app/api/art/image/random/route.tsx
- src/app/api/art/image/random/type.ts
- src/app/api/upload/route.ts
- src/app/art/new/detail/Form.tsx
- src/art/components/detail/ArtDetailForm.tsx
- src/art/image.ts
- src/components/ImageInput/Background.tsx
- src/components/ImageInput/type.ts
- src/upload/upload.ts
- yarn.lock
> [issue-393] 作品登録時の画像自動生成機能を追加

- src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
- src/app/businesscard/[businesscard_id]/edit/actions.ts
> 公開設定押下時のバグ修正

- src/notification/get.ts
close #
read フラグを立てた時にupdateAtが更新されてしまうのでcreateAt順に取得するように修正
出来を10点満点で自己評価:
点
> 作成順で取得するように修正

- src/app/art/[art_id]/Appeals.tsx
> 作品詳細のアピールでプロフィールへのリンクを追加
